### ISSUE TITLE
Auto-generate a web home page for Hackfox

### ISSUE THREAD

**Issue by StevenBlack** [DougHennig/HackFox#1]
Go to [Settings](https://github.com/DougHennig/HackFox/settings) and generate a starter `gh-pages` branch.  See the screen grab below.

I suggest starting with the `Minimal` theme.

Alternally you could do this [manually](https://help.github.com/articles/creating-project-pages-manually/) but ultimately the generator is a good start.

See also [Github Pages](https://pages.github.com/)

![2015-10-21_22-18-27](https://cloud.githubusercontent.com/assets/80144/10655351/c996016c-7841-11e5-8a56-09b0be170f41.jpg)

**Comment by DougHennig** [comment]
Thanks for the suggestion. Done.
